export default {
    LOGIN_ACTION: 'LOGIN_ACTION',
    USER_REQUEST: "GET_USER_REQUEST",
    USER_RESPONSE: "GET_USER_RESPONSE",
    USER_ERROR: "GET_USER_ERROR",
    GET_USER_ACTION: "GET_USER_ACTION",
    SIGN_UP_ACTION: "SIGN_UP_ACTION",
    LOGOUT_ACTION: 'LOGOUT_ACTION',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',

    GET_ALL_EMPLOYEES_ACTION: 'GET_ALL_EMPLOYEES',
    GET_ALL_EMPLOYEES_RESPONSE: 'GET_ALL_EMPLOYEES_RESPONSE',
    EMPLOYEES_ERROR: 'EMPLOYEES_ERROR',

    DELETE_EMPLOYEE_ACTION: 'DELETE_EMPLOYEE_ACTION',

    MODAL_FORM_CHANGE_STATUS_ACTION: 'MODAL_FORM_CHANGE_STATUS_ACTION',

    SAVE_EMPLOYEE_ACTION: 'SAVE_EMPLOYEE_ACTION',
    SAVE_EMPLOYEE_RESPONSE: 'SAVE_EMPLOYEE_RESPONSE',



};